### ISSUE TITLE
question: is there a way to use efb through another computer (browser maybe?)

### ISSUE THREAD

**Issue by g3nsvrv** [flybywiresim/efb#13]
question: is there a way to use efb through another computer (browser maybe?) and integrate it with FS2020?

**Comment by johnhart96** [comment]
I do not think this is possible yet. But I agree this would be a much desirable feature. I wish I had the expertise to write this in myself. Having both the MCDU and the EFB in a browser would be very cool!

**Comment by rgcouto** [comment]
+1 for this feature! 

If any developer of the tool could give me some lights on the repo and this could likely be implemented, I would gladly join the (air)bus!

**Comment by FoxtrotSierra6829** [comment]
duplicate of https://github.com/flybywiresim/aircraft/issues/6978
