### ISSUE TITLE
[Enhancement]: Make the EFB bigger (iPad Pro like vs iPad mini) 

### ISSUE THREAD

**Issue by kmoutot** [flybywiresim/efb#14]
When being in VR mode the current EFB appears to be small even when using the focus mode (right mouse key). Would be great for VR users to have a bigger tablet more in the form factor of an iPad Pro rather than an iPad Mini or iPad Air.

**Comment by FoxtrotSierra6829** [comment]
EFB size has been increased with the recent cockpit overhaul.
https://github.com/flybywiresim/aircraft/pull/8334
